### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by carbonox-infernox** [drons/nbody#3]
I'm confused about running this. You say "To run n-body problem simulation use 'nbody-simulation' programm.", but there is no file named nbody-simulation. The closest is nbody_solver; is that what you meant? Can you give us an example of how to use it?

**Comment by drons** [comment]
Hi!

First you need to compile project.
You can find build scripts at [.travis.yml](https://github.com/drons/nbody/blob/master/.travis.yml) for Linux and at [appveyor.yml](https://github.com/drons/nbody/blob/master/appveyor.yml) for Windows. Or you can open [nbody.pro](https://github.com/drons/nbody/blob/master/nbody.pro) at QtCreator and run build.

After the project is compiled, you can find the simulation program in the directory <build_root>/test/main.

You can find several examples to run [here](https://github.com/drons/nbody/blob/master/.travis.yml#L143).

**Comment by carbonox-infernox** [comment]
Thanks!

I'm on windows, and have tried building with appveyor and QtCreator.

LocalAppveyor says it succeeded, but it did not produce any nbody-simulation in test/main. It was "unable to resolve host address 'opencv-2.4.12-github-vc14-release-travis.rar'", so I installed opencv myself, but that didn't change anything

QtCreator says there are no suitable kits, and google hasn't been any help in resolving that

**Comment by drons** [comment]
It looks like you need to install Qt and register it to QtCreator at Tools->Options->Build&Run

**Comment by carbonox-infernox** [comment]
Qt might be a bit of an issue. I got an email from them saying they pulled my trial license because "free trials are reserved for businesses with commercially viable development projects". Aside from that, it's 50GB, and that's too much for something I'd use once.

I should be able to get this built by manually running everything in that appveyor.yml, right? Might try that if I have time.

**Comment by drons** [comment]
You can download Qt [here](https://www.qt.io/download-qt-installer).

**Comment by drons** [comment]
You can use any Qt version for your choice. There is no special requirements.

**Comment by carbonox-infernox** [comment]
I think it's mostly working now. I'm getting this error about opencv when building:

\nbody\player\nbody_frame_compressor_opencv.cpp:3: error: C1083: Cannot open include file: 'opencv2/opencv.hpp': No such file or directory

**Comment by drons** [comment]
You need to put OpenCV path [here](https://github.com/drons/nbody/blob/master/pri/opencv.pri#L2).
