### ISSUE TITLE
Cannot create engine

### ISSUE THREAD

**Issue by BBBBBbruce** [drons/nbody#4]
Hello, I am trying to build and the run the test on my end. I ran the commands in `nbody_gpu.ipynb`. When I ran the main function I got error 

`build-release/test/main/nbody-simulation --engine=opencl --solver=rkdp --max_time=300 --min_step=0.001 --check_step=5 --stars_count=1024 --verbose=1 --output=alone_galaxy`

`Can't create engine QMap(("check_step", QVariant(QString, "5"))("engine", QVariant(QString, "opencl"))("max_time", QVariant(QString, "300"))("min_step", QVariant(QString, "0.001"))("output", QVariant(QString, "alone_galaxy"))("solver", QVariant(QString, "rkdp"))("stars_count", QVariant(QString, "1024"))("verbose", QVariant(QString, "1")))`

What could be the cause of this issue?
Also, I am not sure if it is relevant, but in the previous section, I got follow results:

> #Runtest
> Invalid tree_layout. Allowed values are 'tree', 'heap' or 'heap_stackless'
> Invalid traverse_type. Allowed values are 'cycle' or 'nested_tree'
> Engine OK!
> Solver OK!
> Stream OK!

Thank you for the help.

**Comment by drons** [comment]
Hi!

You request run at OpenCL engine. Are you really build with OpenCL?

**Comment by BBBBBbruce** [comment]
Hi, for the build I used the 

`cd build-release && qmake ../nbody.pro CONFIG+=release CONFIG+=NO_UI && make -j2 2>build.log 1>/dev/null && echo "Build OK!"` 

I didn't modify anything except the path

**Comment by drons** [comment]
File `nbody_gpu.ipynb` maybe bit outdated.

Please inspect `.travis.yml` and `.github/workflows/analyze.yml` for dependencies for you OS.

If you have custom configuration look at `pri/opencl.pri` for OpenCL config.

Or run on CPU with `--engine=openmp`.
